import type { StreamChannel, RadioStation } from "../types";

// In-memory cache (avoids re-parsing on every render)
let tvCache: StreamChannel[] | null = null;
let tvCacheTime = 0;
let radioCache: RadioStation[] | null = null;
let radioCacheTime = 0;
const CACHE_TTL = 30 * 60 * 1000; // 30 minutes

// ── News TV ─────────────────────────────────────────────────────────────────
// Served from /public/data/news-tv.json generated by scripts/build-news-data.mjs

export async function fetchNewsTV(): Promise<StreamChannel[]> {
  if (tvCache && Date.now() - tvCacheTime < CACHE_TTL) return tvCache;

  try {
    const resp = await fetch("/data/news-tv.json");
    if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
    const data: StreamChannel[] = await resp.json();
    tvCache = data;
    tvCacheTime = Date.now();
    return tvCache;
  } catch (err) {
    console.warn("[fetchNewsTV] failed:", err);
    return tvCache ?? [];
  }
}

// ── News Radio ───────────────────────────────────────────────────────────────
// Radio Browser API — aggressively filtered to actual news stations

const RADIO_HOSTS = [
  "https://de1.api.radio-browser.info",
  "https://fr1.api.radio-browser.info",
  "https://nl1.api.radio-browser.info",
];

interface RadioBrowserStation {
  stationuuid: string;
  name: string;
  url: string;
  url_resolved: string;
  country: string;
  countrycode: string;
  language: string;
  tags: string;
  favicon: string;
  bitrate: number;
  codec: string;
  votes: number;
  clickcount: number;
}

// Keywords that strongly indicate a news/talk-news station
const NEWS_NAME_PATTERNS = [
  /news/i, /noticias/i, /nouvelles/i, /nachrichten/i, /actualit/i,
  /informaci[oó]n/i, /information/i, /informativo/i,
  /nyheter/i, /notícias/i, /noticia/i,
  /khabar/i, /samachar/i,
  /radio journal/i, /journal info/i, /info radio/i, /radio info/i,
  /24\/7 news/i, /all news/i, /news talk/i, /talk news/i,
  /tg\d/i,           // Italian news bulletins TG1, TG2 etc.
  /rfi/i, /rts info/i, /bfm/i, /lci/i, /france info/i,
  /npr/i, /bbc/i, /cnn/i, /msnbc/i, /fox news/i, /abc news/i,
  /euronews/i, /al[ -]jazeera/i, /dw news/i, /france 24/i,
  /sky news/i, /itv news/i, /channel 4 news/i,
  /rtbf info/i, /radio canadá/i,
];

// Tags that indicate the station is NOT primarily news
const NON_NEWS_TAGS = new Set([
  "music", "pop", "rock", "jazz", "classical", "electronic", "hiphop",
  "country music", "reggae", "soul", "rnb", "dance", "techno", "house",
  "metal", "indie", "folk", "blues", "latin music", "salsa", "cumbia",
  "sports", "sport", "comedy", "entertainment", "kids", "children",
  "religion", "religious", "christian", "islam", "gospel",
  "ambient", "chillout", "lounge",
]);

function isNewsStation(s: RadioBrowserStation): boolean {
  const name = s.name.trim();
  if (!name) return false;

  // Must have a working URL
  const url = s.url_resolved || s.url;
  if (!url) return false;

  const tags = s.tags
    ? s.tags.toLowerCase().split(",").map((t) => t.trim())
    : [];

  // If the primary tags are clearly non-news, reject
  const hasNewsTag = tags.includes("news") || tags.includes("news talk");
  const hasMusicOrEntertainmentTag = tags.some((t) => NON_NEWS_TAGS.has(t));

  // Only keep if:
  // A) Has news tag AND does not have conflicting non-news tags as primary type
  //    OR
  // B) Name strongly matches a news pattern (even without explicit tag)
  const nameMatchesNews = NEWS_NAME_PATTERNS.some((pat) => pat.test(name));

  if (hasMusicOrEntertainmentTag && !nameMatchesNews) return false;
  if (!hasNewsTag && !nameMatchesNews) return false;

  return true;
}

async function fetchRadioHost(path: string): Promise<Response> {
  for (const host of RADIO_HOSTS) {
    try {
      const resp = await fetch(`${host}${path}`, {
        headers: { "User-Agent": "Quozix/1.0 (world-news-globe)" },
      });
      if (resp.ok) return resp;
    } catch {
      // try next host
    }
  }
  throw new Error("All Radio Browser hosts failed");
}

export async function fetchNewsRadio(): Promise<RadioStation[]> {
  if (radioCache && Date.now() - radioCacheTime < CACHE_TTL) return radioCache;

  try {
    // Fetch stations tagged "news" — large set, we'll filter client-side
    const resp = await fetchRadioHost(
      "/json/stations/bytag/news?limit=5000&hidebroken=true&order=clickcount&reverse=true"
    );
    const data: RadioBrowserStation[] = await resp.json();

    const filtered = data
      .filter(isNewsStation)
      .filter((s) => (s.url_resolved || s.url).startsWith("http"))
      .map((s) => ({
        id: s.stationuuid,
        name: s.name.trim(),
        country: s.country,
        countryCode: normalizeCountryCode(s.countrycode?.toUpperCase().slice(0, 2) || ""),
        language: s.language || undefined,
        tags: s.tags ? s.tags.split(",").map((t) => t.trim()).filter(Boolean) : [],
        streamUrl: s.url_resolved || s.url,
        favicon: s.favicon || undefined,
        bitrate: s.bitrate || undefined,
        codec: s.codec || undefined,
        votes: s.votes || 0,
        clickCount: s.clickcount || 0,
      }));

    radioCache = filtered;
    radioCacheTime = Date.now();
    return radioCache;
  } catch (err) {
    console.warn("[fetchNewsRadio] failed:", err);
    return radioCache ?? [];
  }
}

// Country code normalization (Radio Browser sometimes uses non-ISO codes)
const CC_NORMALIZE: Record<string, string> = {
  UK: "GB",
  AN: "NL", // Netherlands Antilles
  CS: "RS", // Serbia
};

function normalizeCountryCode(cc: string): string {
  return CC_NORMALIZE[cc] || cc;
}

export function clearNewsCache(): void {
  tvCache = null;
  tvCacheTime = 0;
  radioCache = null;
  radioCacheTime = 0;
}
